server:
  port: 0

spring:
  application:
    name: market-service
  data:
    redis:
      host: localhost # Lưu ý: Khi chạy Docker thì đổi thành 'redis'
      port: 6379

app:
  binance:
    symbols: btcusdt,ethusdt,bnbusdt,solusdt
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true