server:
  port: 0  # Random port cho load balancing

spring:
  application:
    name: market-service
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  binance:
    symbols: btcusdt,ethusdt,bnbusdt,solusdt
    intervals: 1m,5m,15m,1h,4h,1d

eureka:
  instance:
    prefer-ip-address: true