spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_core
    username: admin
    password: admin

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-client-id-here}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret-here}
            scope:
              - email
              - profile
              - openid
            redirect-uri: "http://localhost:8003/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: ${JWT_SECRET:144d4f116a209df65fbaa61977a95a74e0657fc7eeccb0aeec76d364c4e6759f}
    access-token-expiration: 900000 # 15 minutes
    refresh-token-expiration: 604800000 # 7 days
  vnpay:
    return-url: http://localhost:8003/api/v1/payments/vnpay-return

logging:
  level:
    com.crypto: DEBUG
    org.springframework.security: DEBUG
